"""Database Creation

Revision ID: c634ad60217c
Revises: 4b91b7ae280a
Create Date: 2023-06-23 22:13:20.496154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c634ad60217c'
down_revision = '4b91b7ae280a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
